version: "3"

services:
  core_api:
    build:
      context: .
      dockerfile: core_api/Dockerfile.dev
    container_name: core_api
    ports:
      - "8000:8000"
    volumes:
      - ./core_api/app:/core_api/app
      - ./logs:/app/logs
    networks:
      - backend

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - core_api

networks:
  backend:
    driver: bridge
