# Base image
FROM python:3.12

# 작업 디렉토리 설정
WORKDIR /app

# 필수 패키지 설치 (Nginx와 build-essential 설치)
RUN apt-get update && apt-get install -y \
    build-essential \
    nginx \
    && rm -rf /var/lib/apt/lists/*

# base.txt를 통해 공통 의존성 설치
COPY requirements/base.txt /app/requirements/base.txt
RUN pip install --upgrade pip && pip install -r /app/requirements/base.txt

# Nginx 설정 파일 복사
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# FastAPI 애플리케이션 소스 코드 복사
COPY core-api/app /app/app

# Gunicorn을 통한 FastAPI 실행
CMD ["gunicorn", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

# Nginx 실행
CMD service nginx start && gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app --host 0.0.0.0 --port 8000
