FROM python:3.13

# 작업 디렉토리 설정
WORKDIR /app
# 필수 패키지 설치
RUN apt-get update && apt-get install -y \
    build-essential \
    nginx \
    && rm -rf /var/lib/apt/lists/*

# FastAPI와 의존성 설치
COPY ../requirements/base.txt /app/requirements/base.txt
RUN pip install --upgrade pip && pip install --no-cache-dir -r /app/requirements/base.txt
ENV PYTHONPATH="/usr/local/lib/python3.13/site-packages:$PYTHONPATH"

# Nginx 설정 파일 복사
COPY ../nginx/nginx.conf /etc/nginx/nginx.conf

# FastAPI 애플리케이션 소스 코드 복사
COPY . /app/app

# 개발 환경에서 uvicorn 실행
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
